# Generated by Django 4.2.3 on 2023-07-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_image_url'),
    ]

    operations = [
    ]
